services:
  # Servidor Web Nginx
  web:
    image: nginx:alpine
    container_name: servidor_CV
    ports:
      - "90:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
    networks:
      - red_proyecto

  # Servicio de PHP-FPM
  php:
    build: . 
    container_name: php_CV
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - red_proyecto

  # Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: CV_datos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "lolito412/"
      MYSQL_DATABASE: mi_proyecto_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red_proyecto

  # Administrador de BD
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: admin_CV
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=lolito412/
    depends_on:
      - db
    networks:
      - red_proyecto

# Definición de volúmenes y redes
volumes:
  db_data:

networks:
  red_proyecto:
    driver: bridge