services:
  # Servidor Web Nginx
  web:
    image: nginx:alpine
    container_name: servidor_CV
    ports:
      - "90:80" # Tu PC usa el 90, el contenedor usa el 80 (estándar)
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php

  # Servicio de PHP-FPM
  php:
    build: . 
    container_name: php_CV
    volumes:
      - .:/usr/share/nginx/html

  # Base de Datos MySQL
  db:
    image: mysql:8.0 # Cambiado a 8.0 por estabilidad con PHP antiguo
    container_name: CV_datos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "lolito412/"
      MYSQL_DATABASE: mi_proyecto_db
    ports:
      - "3306:3306" # Puerto estándar de MySQL
    volumes:
      - db_data:/var/lib/mysql

  # Administrador de BD
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: admin_CV
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=lolito412/
    depends_on:
      - db

volumes:
  db_data:
